image: nodejs
branches:
  - master
matrix:
  - env: SCRIPT=lint
  - env: SCRIPT=test:coverage
install:
  - npm ci
script:
  - npm run $SCRIPT
deploy:
  - npm ci
  - npm run build
  - mkdir build
  - cp -R packages/backend/build/* build
  - mkdir build/public
  - cp -t build/public packages/frontend/build/*
  - sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWD
  - sudo docker build -t gergof/matrix-token-registration:$(echo $ABSTRUSE_BRANCH | sed -r 's/\//_/g') .
  - sudo docker push gergof/matrix-token-registration:$(echo $ABSTRUSE_BRANCH | sed -r 's/\//_/g')
  - >
    if [ ! -z "$ABSTRUSE_TAG" ]; then
      sudo docker tag gergof/matrix-token-registration:$(echo $ABSTRUSE_BRANCH | sed -r 's/\//_/g') gergof/matrix-token-registration:$ABSTRUSE_TAG
      sudo docker push gergof/matrix-token-registration:$ABSTRUSE_TAG
    fi
  - >
    if [ "$ABSTRUSE_BRANCH" == "master" ] && [ "$ABSTRUSE_EVENT_TYPE" == "push" ]; then
      sudo docker tag gergof/matrix-token-registration:$(echo $ABSTRUSE_BRANCH | sed -r 's/\//_/g') gergof/matrix-token-registration:latest
      sudo docker push gergof/matrix-token-registration:latest
    fi
